# Generated by Django 4.2.23 on 2025-08-23 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("club", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ledger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("amount", models.IntegerField()),
                (
                    "account",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="accounts.accounts"
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="club.clubmember"),
                ),
                (
                    "club",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="club.club", verbose_name=""),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="receipts/")),
                ("ocr_text", models.TextField()),
                ("amount", models.IntegerField()),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LedgerTransactions",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("date", models.DateField()),
                ("amount", models.IntegerField()),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("payment_method", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("ledger", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ledger.ledger")),
                (
                    "receipt",
                    models.OneToOneField(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="ledger.receipt"
                    ),
                ),
            ],
        ),
    ]
