# Generated by Django 4.2.23 on 2025-08-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgertransactions",
            name="vendor",
            field=models.CharField(default="거래처", max_length=100),
            preserve_default=False,
        ),
    ]
