# Generated by Django 4.2.23 on 2025-08-25 12:56

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0004_restore_auto_now_add"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ledgertransactions",
            name="date",
        ),
        migrations.AddField(
            model_name="ledgertransactions",
            name="date_time",
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ledger",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ledgertransactions",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ledgertransactions",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
