# Generated by Django 4.2.23 on 2025-08-25 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0001_initial"),
        ("ledger", "0005_remove_ledgertransactions_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.TextField()),
                ("club", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="club.club")),
            ],
        ),
    ]
