# Generated by Django 4.2.23 on 2025-08-25 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0006_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgertransactions",
            name="event",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="ledger.event"),
        ),
    ]
