# Generated by Django 4.2.23 on 2025-08-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_ledgertransactions_vendor"),
        ("ledger", "0007_ledgertransactions_event"),
    ]

    operations = []
