# Generated by Django 4.2.23 on 2025-08-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0008_merge_20250826_0046"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="budget",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
