# Generated by Django 4.2.23 on 2025-08-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0009_event_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
