# Generated by Django 4.2.23 on 2025-08-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0010_alter_event_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="processed_text",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
    ]
