# Generated by Django 4.2.23 on 2025-08-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0011_receipt_processed_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipt",
            old_name="created_at",
            new_name="date_time",
        ),
        migrations.RenameField(
            model_name="receipt",
            old_name="processed_text",
            new_name="items",
        ),
    ]
