# Generated by Django 4.2.23 on 2025-08-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0012_rename_created_at_receipt_date_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="ocr_text",
        ),
    ]
