# Generated by Django 4.2.23 on 2025-08-29 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0003_club_image"),
        ("ledger", "0013_remove_receipt_ocr_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerTransactionsComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="club.clubmember")),
                (
                    "transaction",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ledger.ledgertransactions"),
                ),
            ],
        ),
    ]
