# Generated by Django 4.2.15 on 2025-08-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0014_ledgertransactionscomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgertransactions",
            name="external_id",
            field=models.CharField(
                blank=True, help_text="외부 API의 거래 고유 ID", max_length=50, null=True, unique=True
            ),
        ),
    ]
