# Generated by Django 4.2.23 on 2025-08-23 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accounts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.IntegerField()),
                ("code", models.CharField(max_length=50)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.user")),
            ],
        ),
        migrations.CreateModel(
            name="AccountTransactions",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("occurred_at", models.DateTimeField()),
                ("amount", models.IntegerField()),
                ("memo", models.TextField()),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.accounts")),
            ],
        ),
    ]
