# Generated by Django 4.2.23 on 2025-08-28 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0003_club_image"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="club",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="club.club"
            ),
        ),
    ]
