# Generated by Django 4.2.23 on 2025-08-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accounts",
            name="product",
        ),
    ]
