# Generated by Django 4.2.23 on 2025-08-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_accounts_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="product",
            field=models.CharField(default="중앙동아리", max_length=100),
            preserve_default=False,
        ),
    ]
