# Generated by Django 4.2.23 on 2025-08-21 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerReports",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("ledger", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ledger.ledger")),
            ],
        ),
    ]
