# Generated by Django 4.2.23 on 2025-08-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger_report", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerreports",
            name="content",
            field=models.JSONField(),
        ),
    ]
