# Generated by Django 4.2.23 on 2025-08-23 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("student_number", models.CharField(db_index=True, max_length=50, unique=True)),
                (
                    "admission_year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1950),
                            django.core.validators.MaxValueValidator(2025),
                        ]
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?\\d{7,15}$", message="전화번호 형식이 올바르지 않습니다."
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "재학중"),
                            ("absence", "휴학중"),
                            ("expelled", "제적"),
                            ("graduated", "졸업"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("profile_url_image", models.URLField(blank=True)),
                ("user_key", models.CharField(blank=True, db_index=True, max_length=200, null=True)),
            ],
        ),
    ]
