# Generated by Django 4.2.23 on 2025-08-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("student_number", models.CharField(max_length=50, unique=True)),
                ("admission_year", models.IntegerField()),
                ("phone_number", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "재학중"),
                            ("absence", "휴학중"),
                            ("expelled", "제적"),
                            ("graduated", "졸업"),
                        ],
                        max_length=50,
                    ),
                ),
                ("profile_url_image", models.TextField()),
            ],
        ),
    ]
