# Generated by Django 4.2.23 on 2025-08-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="김싸피", max_length=20),
            preserve_default=False,
        ),
    ]
