# Generated by Django 4.2.23 on 2025-08-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="major",
            field=models.CharField(default="전공", max_length=20),
            preserve_default=False,
        ),
    ]
