# Generated by Django 4.2.23 on 2025-08-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_major"),
        ("user", "0002_user_name"),
    ]

    operations = []
