# Generated by Django 4.2.23 on 2025-08-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_merge_0002_user_major_0002_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="major",
        ),
    ]
