# Generated by Django 4.2.23 on 2025-08-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_user_major"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="major",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
