# Generated by Django 4.2.23 on 2025-08-21 06:43

import django.db.models.deletion
from django.db import migrations, models

import club.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                (
                    "major_category",
                    models.CharField(
                        choices=[
                            ("academic", "학술"),
                            ("sports", "체육"),
                            ("culture", "문화예술"),
                            ("volunteer", "봉사"),
                            ("entrepreneur", "창업"),
                            ("religion", "종교"),
                        ],
                        max_length=20,
                    ),
                ),
                ("minor_category", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("hashtags", models.TextField()),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClubMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "활동중"),
                            ("absence", "휴학중"),
                            ("expelled", "탈퇴"),
                            ("graduated", "졸업"),
                            ("waiting", "가입 대기 중"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("leader", "회장"), ("officer", "간부"), ("member", "부원")],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateField(auto_now_add=True)),
                ("amount_fee", models.IntegerField()),
                ("paid_fee", models.IntegerField()),
                ("club", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="club.club")),
                ("user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="user.user")),
            ],
        ),
        migrations.CreateModel(
            name="Dues",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.IntegerField()),
                ("due_to", models.DateField()),
                ("paid_at", models.DateField(blank=True, null=True)),
                ("member", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="club.clubmember")),
            ],
        ),
    ]
