# Generated by Django 4.2.23 on 2025-08-24 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="location",
            field=models.TextField(default="미기재"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="club",
            name="short_description",
            field=models.TextField(default="1줄 소개입니다"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ClubWelcomePage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="welcome/")),
                ("content", models.TextField()),
                ("club", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="club.club")),
            ],
        ),
    ]
