# Generated by Django 4.2.23 on 2025-08-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="department",
            field=models.CharField(default="중앙동아리", max_length=20),
            preserve_default=False,
        ),
    ]
