# Generated by Django 4.2.23 on 2025-08-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0002_club_location_club_short_description_clubwelcomepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="club/"),
        ),
    ]
