# Generated by Django 4.2.23 on 2025-08-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0003_club_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="dues",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
