# Generated by Django 4.2.23 on 2025-08-30 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0004_dues_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="dues",
            name="club",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="club.club"),
        ),
    ]
