# Generated by Django 4.2.23 on 2025-08-23 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("club", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(choices=[("announcement", "공지"), ("forum", "자유 게시판")], max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("views", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="club.clubmember"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="club.clubmember")),
                ("board", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="boards.board")),
            ],
        ),
        migrations.CreateModel(
            name="AttachedFiles",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="attached_files/")),
                ("board", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="boards.board")),
            ],
        ),
        migrations.CreateModel(
            name="CommentLikes",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="boards.comments")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="club.clubmember")),
            ],
            options={
                "unique_together": {("comment", "user")},
            },
        ),
        migrations.CreateModel(
            name="BoardLikes",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("board", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="boards.board")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="club.clubmember")),
            ],
            options={
                "unique_together": {("board", "user")},
            },
        ),
    ]
