# Generated by Django 4.2.23 on 2025-08-23 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0001_initial"),
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="club",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="club.club"),
            preserve_default=False,
        ),
    ]
