# Generated by Django 4.2.23 on 2025-08-21 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boards", "0001_initial"),
        ("club", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="author",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="club.clubmember"),
        ),
        migrations.AddField(
            model_name="comments",
            name="board",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="boards.board"),
        ),
        migrations.AddField(
            model_name="commentlikes",
            name="comment",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="boards.comments"),
        ),
        migrations.AddField(
            model_name="commentlikes",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="club.clubmember"),
        ),
        migrations.AddField(
            model_name="boardlikes",
            name="board",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="boards.board"),
        ),
        migrations.AddField(
            model_name="boardlikes",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="club.clubmember"),
        ),
        migrations.AddField(
            model_name="board",
            name="author",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="club.clubmember"),
        ),
        migrations.AddField(
            model_name="attachedfiles",
            name="board",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="boards.board"),
        ),
        migrations.AlterUniqueTogether(
            name="commentlikes",
            unique_together={("comment", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="boardlikes",
            unique_together={("board", "user")},
        ),
    ]
